version: "3.3"

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: gio-app
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www

  nginx:
    image: nginx:1.19-alpine
    container_name: gio-nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d