version: "3.3"

services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: gio-app
    restart: always
    working_dir: /var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../src:/var/www

  nginx:
    image: nginx:1.19-alpine
    container_name: gio-nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: gio-db
    image: mysql:8.0
    volumes:
     - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password    
    ports:
       - 3307:3306
        
        

